FROM java

MAINTAINER lujiahao0708@gmail.com

COPY /project/blog-web/target/blog-web-0.0.1.jar /usr/src/myapp/blog-web-0.0.1.jar
COPY /project/agent    /usr/src/myapp/agent

WORKDIR /usr/src/myapp/

ENTRYPOINT java -javaagent:/usr/src/myapp/agent/skywalking-agent.jar -jar blog-web-0.0.1.jar
